#!/bin/bash

CACHE="$HOME/.cache/wallpapers.list"

# builds cache list based on timestamp
~/.config/hypr/scripts/cache_wallpaper_list

# read cache into array
mapfile -t WALLS < "$CACHE"

[[ ${#WALLS[@]} -eq 0 ]] && exit 1

WALL="${WALLS[RANDOM % ${#WALLS[@]}]}"

ln -sf "$WALL" ~/.cache/wal/current
awww img "$WALL" --transition-type grow --transition-duration 1.2
wal -i "$WALL"

