# ss dir env var is set in ~/.zprofile
###################
### KEYBINDINGS ###
###################

# Screenshot a window
bind = ALT, PRINT, exec, hyprshot -m window
# Screenshot a monitor
bind = $mainMod, PRINT, exec, hyprshot -m output
# Screenshot a region
bind = , PRINT, exec, hyprshot -m region
